model:
  pretrained_name: "/llm_reco/dehua/model/Qwen2.5-VL-7B-Instruct"  # or your本地路径
  num_labels: 101

data:
  train_jsonl: "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food101_train.jsonl"  # Changed to jsonl format
  val_jsonl:   "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food101_test.jsonl"    # Changed to jsonl format

training:
  epochs:          10
  micro_batch_size_per_gpu: 16  # micro batch size per GPU
  gradient_accumulation_steps: 4  # effective batch size = micro_batch_size_per_gpu * gradient_accumulation_steps * num_gpus
  lr:              2e-5
  weight_decay:    0.01
  warmup_steps:    500
  output_dir:      "./outputs"
  logging_steps:   50
  save_steps:      1000
  num_workers:     4
  use_fused_adam:  true  # Use FusedAdam for better performance

# DeepSpeed specific settings
deepspeed:
  config_file: "configs/ds_s2.json"
  zero_stage: 2
  fp16: true
  
# Weights & Biases configuration
wandb:
  enabled: true  # Set to false to disable wandb logging
  project: "qwen_classification"  # wandb project name
  run_name: null  # Optional run name, will be auto-generated if null
  tags: ["qwen", "deepspeed", "classification"]  # Optional tags
  notes: "Qwen2.5-VL classification training"  # Optional notes

# Legacy accelerate settings (for compatibility)
accelerate:
  gradient_accumulation_steps: 4  # Updated to match training config
  fp16: true