model:
  pretrained_name: "/llm_reco/dehua/model/Qwen2.5-VL-7B-Instruct"
  num_labels: 172  # Food101的类别数

# 损失函数配置
# 损失函数配置
loss:
  type: "cross_entropy"  # 选项: cross_entropy, focal, label_smoothing, arcface, symmetric_ce

# 单数据集配置
datasets:
  dataset_configs:
    food172:
      num_classes: 172
      description: "Food172 dataset"
      eval_ratio: 1  # 训练过程中评估20%的数据
  # 单数据集不需要logits masking
  enable_logits_masking: false
  # 单数据集不需要shuffle
  shuffle_datasets: false

data:
  # 单数据集使用原始格式
  train_jsonl: "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food172_train.jsonl"
  val_jsonl: "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food172_test.jsonl"

training:
  epochs: 10
  lr: 1e-6
  weight_decay: 0.01
  warmup_steps: 0.1
  output_dir: "/mmu_mllm_hdd_2/madehua/model/qwen_classify/food172_1e_6"
  logging_steps: 5000
  save_steps: 200
  eval_steps: 200
  save_hf_format: true
  save_deepspeed_format: false
  num_workers: 32
  use_fused_adam: true
  
  # 学习率调度器配置
  lr_scheduler:
    type: "cosine"  # 余弦调度器
    final_lr_ratio: 0.1  # 最终学习率为初始学习率的5% (20倍衰减)
    num_cycles: 0.5  # 余弦周期数
  
  # 最佳模型追踪配置
  best_model_tracking:
    enabled: true
    metric: "overall_accuracy"  # 追踪的指标
    mode: "max"  # max 或 min
    save_best_only: true  # 是否只保存最佳模型
  
  # 评估配置
  evaluation:
    partial_eval_during_training: true  # 训练过程中是否进行部分评估
    full_eval_at_end: true  # 训练结束后是否进行完整评估
    eval_best_model_only: true  # 是否只对最佳模型进行完整评估

# DeepSpeed specific settings
deepspeed:
  config_file: "configs/ds_s2.json"
  zero_stage: 2
  bf16: true

# Weights & Biases configuration
wandb:
  enabled: true
  project: "qwen_classification"
  run_name: "food172_cosine_5e_6_ls"
  tags: ["qwen", "deepspeed", "classification", "cosine_hold", "single_dataset"]
  notes: "Qwen2.5-VL Food101 classification with cosine+hold scheduler"
  log_dataset_metrics: false  # 单数据集不需要按数据集分组的指标
  log_overall_metrics: true   # 记录整体指标

# Legacy accelerate settings (for compatibility)
accelerate:
  bf16: true 