model:
  pretrained_name: "/llm_reco/dehua/model/Qwen2.5-VL-7B-Instruct"
  num_labels: 101  # Food101的类别数

# 损失函数配置
loss:
  type: "cross_entropy"  # 选项: cross_entropy, focal, label_smoothing, arcface, symmetric_ce

# 单数据集配置 - 快速评估版本
datasets:
  dataset_configs:
    food101:
      num_classes: 101
      description: "Food-101 dataset"
      eval_ratio: 0.1  # 训练过程中只评估10%的数据，极速评估
  # 单数据集不需要logits masking
  enable_logits_masking: false
  # 单数据集不需要数据集级shuffle
  shuffle_datasets: false

data:
  # 单数据集使用原始格式
  train_jsonl: "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food101_train.jsonl"
  val_jsonl: "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food101_test.jsonl"

training:
  epochs: 5
  lr: 1e-5
  weight_decay: 0.01
  warmup_steps: 200
  output_dir: "/mmu_mllm_hdd_2/madehua/model/qwen_classify/food101_fast_eval"
  logging_steps: 50
  save_steps: 200
  eval_steps: 1000  # 大幅增加评估间隔，减少评估频率
  save_hf_format: true
  save_deepspeed_format: false
  num_workers: 16
  use_fused_adam: true
  gradient_checkpointing: false
  
  # 学习率调度器配置
  lr_scheduler:
    type: "cosine_with_hold"  # 余弦+平稳期调度器
    hold_ratio: 0.4  # 平稳期占非warmup步数的40%
    final_lr_ratio: 0.1  # 最终学习率为初始学习率的10%
    num_cycles: 0.5  # 余弦周期数
  
  # 最佳模型追踪配置
  best_model_tracking:
    enabled: true
    metric: "overall_accuracy"  # 追踪的指标
    mode: "max"  # max 或 min
    save_best_only: true  # 是否只保存最佳模型
  
  # 评估配置 - 快速评估版本
  evaluation:
    partial_eval_during_training: true  # 训练过程中进行部分评估（10%数据）
    full_eval_at_end: true  # 训练结束后进行完整评估（100%数据）
    eval_best_model_only: true  # 只对最佳模型进行完整评估

# DeepSpeed配置通过命令行参数传入，不在此处设置

# Weights & Biases configuration
wandb:
  enabled: true
  project: "qwen_classification"
  run_name: "food101_fast_eval"
  tags: ["qwen", "deepspeed", "classification", "fast_eval", "single_dataset"]
  notes: "Qwen2.5-VL Food101 classification with fast evaluation (10% eval data)"
  log_dataset_metrics: false  # 单数据集不需要按数据集分组的指标
  log_overall_metrics: true   # 记录整体指标 