# 监控频率配置示例
# 将此配置添加到你的训练配置文件中

# 统一频率设置（推荐且唯一支持的方式）
monitor:
  freq:
    all_freq: 100  # 统一基础频率，其他频率将按比例自动计算
    # 自动计算结果：
    # - training_log_freq: 100（每100步记录训练指标）
    # - perf_log_freq: 200（每200步记录性能指标）
    # - gpu_log_freq: 400（每400步记录GPU指标）
    # - flops_profile_freq: 200（与perf频率一致，确保MFU数据同步）
    # - local_save_freq: 2000（每2000步保存本地日志）
    # - progress_update_freq: 20（每20步更新进度条）

---
# 完整配置示例（添加到现有的config.yaml中）
model:
  model_name: "Qwen/Qwen2.5-VL-7B-Instruct"
  max_sequence_length: 2048
  num_classes: 101

training:
  num_epochs: 3
  learning_rate: 3e-6
  weight_decay: 0.01
  warmup_steps: 100

# 添加监控配置
monitor:
  freq:
    all_freq: 100  # 根据需要调整：20(详细) | 50(平衡) | 100(高吞吐)

deepspeed:
  train_batch_size: 64
  train_micro_batch_size_per_gpu: 8
  gradient_accumulation_steps: 1

wandb:
  project: "qwen_classify"
  name: "experiment_1" 