model:
  pretrained_name: "/llm_reco/dehua/model/Qwen2.5-VL-7B-Instruct"
  num_labels: 2000

loss:
  type: "cross_entropy"

datasets:
  dataset_configs:
    food101:
      num_classes: 101
      description: "Food-101 dataset"
      eval_ratio: 0.2
    food2k:
      num_classes: 2000
      description: "Food2K dataset"
      eval_ratio: 0.1
    food172:
      num_classes: 172
      description: "Food172 dataset"
      eval_ratio: 0.2
  enable_logits_masking: true
  shuffle_datasets: true

data:
  train_jsonl_list:
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food101_train.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food172_train.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food2k_train.jsonl"
  val_jsonl_list:
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food101_test.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food172_test.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food2k_test.jsonl"

training:
  epochs: 5
  lr: 1e-5
  weight_decay: 0.01
  warmup_steps: 200
  output_dir: "/mmu_mllm_hdd_2/madehua/model/qwen_classify/multi_datasets_linear_lr"
  logging_steps: 50
  save_steps: 500
  eval_steps: 500
  save_hf_format: true
  save_deepspeed_format: true
  num_workers: 16
  use_fused_adam: true
  
  # 线性学习率调度器配置
  lr_scheduler:
    type: "linear"  # 线性衰减调度器
    final_lr_ratio: 0.05  # 最终学习率为初始学习率的5%
  
  best_model_tracking:
    enabled: true
    metric: "overall_accuracy"
    mode: "max"
    save_best_only: true
  
  evaluation:
    partial_eval_during_training: true
    full_eval_at_end: true
    eval_best_model_only: true

deepspeed:
  config_file: "configs/ds_s2.json"
  zero_stage: 2
  bf16: true

wandb:
  enabled: true
  project: "qwen_multi_datasets"
  run_name: "linear_scheduler_test"
  tags: ["qwen", "deepspeed", "multi-datasets", "linear-lr"]
  notes: "Testing linear learning rate scheduler"
  log_dataset_metrics: true
  log_overall_metrics: true

accelerate:
  bf16: true 