model:
  pretrained_name: "/llm_reco/dehua/model/Qwen2.5-VL-7B-Instruct"  # or your本地路径
  num_labels: 2000  # 所有数据集中的最大类别数

# 损失函数配置
loss:
  type: "cross_entropy"  # 选项: cross_entropy, focal, label_smoothing, arcface, symmetric_ce

# 多数据集配置
datasets:
  dataset_configs:
    food101:
      num_classes: 101
      description: "Food-101 dataset"
      eval_ratio: 0.2  # 训练过程中评估20%的数据
    food2k:
      num_classes: 2000
      description: "Food2K dataset"
      eval_ratio: 0.1  # 训练过程中评估10%的数据
    food172:
      num_classes: 172
      description: "Food172 dataset"
      eval_ratio: 0.2  # 训练过程中评估10%的数据
    foodx251:
      num_classes: 251
      description: "foodx251 dataset"
      eval_ratio: 0.2  # 训练过程中评估10%的数据
    fru92:
      num_classes: 92
      description: "fru92 dataset"
      eval_ratio: 0.2  # 训练过程中评估10%的数据
    veg200:
      num_classes: 200
      description: "veg200 dataset"
      eval_ratio: 0.2  # 训练过程中评估10%的数据
  # 如果为true，在预测时会根据数据集名称mask无效的logits
  enable_logits_masking: true
  # 是否将所有数据集的数据混合并shuffle
  shuffle_datasets: true

data:
  # 支持多个训练数据文件路径
  train_jsonl_list:
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food101_train.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food172_train.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/foodx251_train.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food2k_train.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/fru92_train.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/veg200_train.jsonl"
  # 支持多个验证数据文件路径
  val_jsonl_list:
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food101_test.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food172_test.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/foodx251_test.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food2k_test.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/fru92_test.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/veg200_test.jsonl"

training:
  epochs:          5
  lr:              1e-5
  weight_decay:    0.01
  warmup_steps:    200
  output_dir:      "/mmu_mllm_hdd_2/madehua/model/qwen_classify/multi_datasets_1e_5"
  logging_steps:   50  # Log training metrics every N steps
  save_steps:      500  # Save checkpoint every N steps
  eval_steps:      10  # Evaluate model every N steps (临时改为10用于测试)
  save_hf_format:  true  # Save HuggingFace format during training
  save_deepspeed_format: true  # Save DeepSpeed format (only needed for resuming training)
  num_workers:     16  # Set to 0 to avoid multiprocessing issues
  use_fused_adam:  true  # Use FusedAdam for better performance
  
  # 学习率调度器配置
  lr_scheduler:
    type: "cosine"  # 可选: cosine, linear, polynomial, exponential, constant, cosine_restarts
    final_lr_ratio: 0.1  # 最终学习率相对于初始学习率的比例 (10%)
    # cosine调度器特有参数
    num_cycles: 0.5  # 余弦周期数，默认0.5
    # polynomial调度器特有参数
    # power: 1.0  # 多项式幂次，默认1.0
    # exponential调度器特有参数  
    # decay_rate: 0.95  # 指数衰减率，默认0.95
    # cosine_restarts调度器特有参数
    # restart_period_epochs: 2  # 重启周期（epochs），默认2
  
  # 最佳模型追踪配置
  best_model_tracking:
    enabled: true
    metric: "overall_accuracy"  # 追踪的指标
    mode: "max"  # max 或 min
    save_best_only: true  # 是否只保存最佳模型
  
  # 评估配置
  evaluation:
    partial_eval_during_training: true  # 训练过程中是否进行部分评估
    full_eval_at_end: true  # 训练结束后是否进行完整评估
    eval_best_model_only: true  # 是否只对最佳模型进行完整评估

# DeepSpeed specific settings
deepspeed:
  config_file: "configs/ds_s2.json"
  zero_stage: 2
  bf16: true  # Using BF16 instead of FP16
  
# Weights & Biases configuration
wandb:
  enabled: true  # Set to false to disable wandb logging
  project: "qwen_multi_datasets"  # wandb project name
  run_name: null  # Optional run name, will be auto-generated if null
  tags: ["qwen", "deepspeed", "multi-datasets", "classification"]  # Optional tags
  notes: "Qwen2.5-VL multi-datasets classification training"  # Optional notes
  log_dataset_metrics: true  # 是否记录按数据集分组的指标
  log_overall_metrics: true  # 是否记录整体指标（所有样本）

# Legacy accelerate settings (for compatibility)
accelerate:
  bf16: true  # Using BF16 instead of FP16
  # Note: gradient_accumulation_steps is now managed by DeepSpeed (ds_s2.json)