model:
  pretrained_name: "/llm_reco/dehua/model/Qwen2.5-VL-7B-Instruct"
  num_labels: 2000  # Food101的类别数

# 损失函数配置
# 损失函数配置
loss:
  type: "label_smoothing"  # 选项: cross_entropy, focal, label_smoothing, arcface, symmetric_ce
  smoothing: 0.1
  temperature: 1.0

# 统一频率设置（推荐且唯一支持的方式）
monitor:
  freq:
    training_log_freq: 200      # 训练指标记录频率
    eval_log_freq: 1            # 评估指标记录频率
    perf_log_freq: 200          # 性能指标记录频率
    gpu_log_freq: 200           # GPU监控频率
    flops_profile_freq: 200     # MFU计算频率 (使用profiler)
    local_save_freq: 200       # 本地日志保存频率
    progress_update_freq: 200    # 进度更新频率

# 多数据集配置
datasets:
  dataset_configs:
    food101:
      num_classes: 101
      description: "Food-101 dataset"
      eval_ratio: 0.2  # 训练过程中评估20%的数据
    food2k:
      num_classes: 2000
      description: "Food2K dataset"
      eval_ratio: 0.1  # 训练过程中评估10%的数据
    food172:
      num_classes: 172
      description: "Food172 dataset"
      eval_ratio: 0.2  # 训练过程中评估10%的数据
    foodx251:
      num_classes: 251
      description: "foodx251 dataset"
      eval_ratio: 0.2  # 训练过程中评估10%的数据
    fru92:
      num_classes: 92
      description: "fru92 dataset"
      eval_ratio: 0.2  # 训练过程中评估10%的数据
    veg200:
      num_classes: 200
      description: "veg200 dataset"
      eval_ratio: 0.2  # 训练过程中评估10%的数据
  # 如果为true，在预测时会根据数据集名称mask无效的logits
  enable_logits_masking: false
  # 是否将所有数据集的数据混合并shuffle
  shuffle_datasets: true

data:
  # 支持多个训练数据文件路径
  train_jsonl_list:
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food101_train.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food172_train.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/foodx251_train.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food2k_train.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/fru92_train.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/veg200_train.jsonl"
  # 支持多个验证数据文件路径
  val_jsonl_list:
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food101_test.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food172_test.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/foodx251_test.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/food2k_test.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/fru92_test.jsonl"
    - "/llm_reco/dehua/code/qwen_classify/data/dataset_food_label/veg200_test.jsonl"

training:
  epochs: 5
  lr: 5e-6
  weight_decay: 0.01
  warmup_steps: 0.1
  output_dir: "/mmu_mllm_hdd_2/madehua/model/qwen_classify/multi_ls_5e_6_epoch5"
  logging_steps: 50000
  save_steps: 1000
  eval_steps: 1000
  save_hf_format: true
  save_deepspeed_format: true
  num_workers: 32
  use_fused_adam: true
  gradient_checkpointing: false

  # 学习率调度器配置
  lr_scheduler:
    type: "cosine"  # 余弦调度器
    final_lr_ratio: 0.1  # 最终学习率为初始学习率的5% (20倍衰减)
    num_cycles: 0.5  # 余弦周期数
  
  # 最佳模型追踪配置
  best_model_tracking:
    enabled: true
    metric: "overall_accuracy"  # 追踪的指标
    mode: "max"  # max 或 min
    save_best_only: false  # 是否只保存最佳模型
  
  # 评估配置
  evaluation:
    partial_eval_during_training: true  # 训练过程中是否进行部分评估
    full_eval_at_end: true  # 训练结束后是否进行完整评估
    eval_best_model_only: true  # 是否只对最佳模型进行完整评估

# DeepSpeed specific settings
deepspeed:
  config_file: "configs/ds_s2.json"
  zero_stage: 2
  bf16: true

# Weights & Biases configuration
wandb:
  enabled: true
  project: "qwen_classification"
  run_name: "multi_datasets_epoch5"
  tags: ["qwen", "deepspeed", "classification", "cosine_hold", "single_dataset"]
  notes: "Qwen2.5-VL Food101 classification with cosine+hold scheduler"
  log_dataset_metrics: false  # 单数据集不需要按数据集分组的指标
  log_overall_metrics: true   # 记录整体指标

# Legacy accelerate settings (for compatibility)
accelerate:
  bf16: true 